### ISSUE TITLE
NodeSecurityGroupFromControlPlaneIngress in amazon-eks-nodegroup.yaml template is very limiting

### ISSUE THREAD

**Issue by ilyasotkov** [awsdocs/amazon-eks-user-guide#11]
In the `amazon-eks-nodegroup.yaml` template that is linked from this guide, there is this security group:

```yaml
  NodeSecurityGroupFromControlPlaneIngress:
    Type: AWS::EC2::SecurityGroupIngress
    DependsOn: NodeSecurityGroup
    Properties:
      Description: Allow worker Kubelets and pods to receive communication from the cluster control plane
      GroupId: !Ref NodeSecurityGroup
      SourceSecurityGroupId: !Ref ClusterControlPlaneSecurityGroup
      IpProtocol: tcp
      FromPort: 1025
      ToPort: 65535
```

Basically, this setting makes it impossible for Kubernetes services to access pods that have have containerPort set to anything below 1025, which is a huge issue since so many of them use the 80 port (e.g. nginx).

So, the question is: why is this set to 1025, not 0?
