### ISSUE TITLE
Passing AWS_PROFILE on update-kubeconfig cli

### ISSUE THREAD

**Issue by dileep-p** [awsdocs/amazon-eks-user-guide#21]
Add profile details if calling update passing update-kubeconfig with  profile details 

#aws eks update-kubeconfig --name k8s-test --kubeconfig k8s-test.config --profile myprofile 

Currently this generates as 
```
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - k8s-test
      command: aws-iam-authenticator
```

Its good to add the profile details on the cli when not using default profile. 

```
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "k8s-test"

      env:
        - name: AWS_PROFILE
          value: "myprofile"
```
