### ISSUE TITLE
Question: Must aws-observability Namespace have `aws-observability: enabled` label ?

### ISSUE THREAD

**Issue by mikutas** [awsdocs/amazon-eks-user-guide#452]
https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/fargate-logging.md#log-router-configuration

```yaml
kind: Namespace
apiVersion: v1
metadata:
  name: aws-observability
  labels:
    aws-observability: enabled # <- this label
```
