### ISSUE TITLE
Kubelet not ready on nodes

### ISSUE THREAD

**Issue by wh1sssss** [awsdocs/amazon-eks-user-guide#454]
Hello folks,

I need a help with runtime containerd running on  worker nodes kubelet version 1.21.

Attention on image, i use from:

https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html

I have created my cluster with the file below:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-xxx
  region: us-east-1
  version: "1.21"
  tags:
    managed: eksctl
    owner: eks-xxx

vpc:
  id: "vpc-xxxx"
  securityGroup: "sg-xxx"
  subnets:
    private:
        us-east-1a:
          id: "subnet-xxxx"
        us-east-1b:
          id: "subnet-xxxx"
        us-east-1c:
          id: "subnet-xxxx"
    public:
        us-east-1a:
          id: "subnet-yyyyy"
        us-east-1b:
          id: "subnet-yyyyy"
        us-east-1c:
          id: "subnet-yyyyy"

nodeGroups:
  - name: gp01
    volumeSize: 50
    volumeType: gp2
    ami: **ami-0193ebf9573ebc9f7**
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh eks-xxx --container-runtime containerd
    privateNetworking: true
    minSize: 1
    maxSize: 2
    instancesDistribution:
        maxPrice: 0.095000
        instanceTypes:
          - "t4g.xlarge"
          - "t3.xlarge"
          - "t2.xlarge"
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 0
        spotInstancePools: 4
    securityGroups:
        withShared: true
        withLocal: true
    iam:
      attachPolicyARNs:
        - arn:aws:iam::983054731403:policy/eks-xxx-xxx
      withAddonPolicies:
        ALBIngress: true
        AutoScaler: true
        CertManager: true
        CloudWatch: true
        EBS: true
        EFS: true
        ExternalDNS: true
        ImageBuilder: true # ECR
        XRay: true
    ssh:
      publicKeyPath: ./keys/eks-xxx

cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator"]
```

Everything went well until the part of creating the node group, it creates the nodes but does not attach to the cluster, when logging into the node I received the following logs from kubelete.

**Command to see logs:**

`sudo cat /var/log/messages`

**Logs:**
`Sep  9 20:39:33 ip-10-53-2-218 systemd: Started Session c320 of user root.
Sep  9 20:39:33 ip-10-53-2-218 containerd: time="2021-09-09T20:39:33.807930482Z" level=info msg="ImageUpdate event &ImageUpdate{Name:602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause:3.1-eksbuild.1,Labels:map[string]string{},XXX_unrecognized:[],}"
Sep  9 20:39:33 ip-10-53-2-218 containerd: time="2021-09-09T20:39:33.821960041Z" level=info msg="ImageUpdate event &ImageUpdate{Name:sha256:106a8e54d5eb3f70fcd1ed46255bdf232b3f169e89e68e13e4e67b25f59c1315,Labels:map[string]string{io.cri-containerd.image: managed,},XXX_unrecognized:[],}"
Sep  9 20:39:33 ip-10-53-2-218 containerd: time="2021-09-09T20:39:33.822587955Z" level=info msg="ImageUpdate event &ImageUpdate{Name:602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause:3.1-eksbuild.1,Labels:map[string]string{io.cri-containerd.image: managed,},XXX_unrecognized:[],}"
Sep  9 20:39:33 ip-10-53-2-218 pull-sandbox-image.sh: 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause:3.1-eksbuild.1: resolving      |#033[32m#033[0m--------------------------------------|
Sep  9 20:39:33 ip-10-53-2-218 pull-sandbox-image.sh: elapsed: 0.1 s                                                         total:   0.0 B (0.0 B/s)
Sep  9 20:39:33 ip-10-53-2-218 pull-sandbox-image.sh: 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause:3.1-eksbuild.1:            resolved       |#033[32m++++++++++++++++++++++++++++++++++++++#033[0m|
Sep  9 20:39:33 ip-10-53-2-218 pull-sandbox-image.sh: index-sha256:1cb4ab85a3480446f9243178395e6bee7350f0d71296daeb6a9fdd221e23aea6:    done           |#033[32m++++++++++++++++++++++++++++++++++++++#033[0m|
Sep  9 20:39:33 ip-10-53-2-218 pull-sandbox-image.sh: manifest-sha256:234b8785dd78afc0fbb27edad009e7eb253e5685fb7387d4f0145f65c00873ac: done           |#033[32m++++++++++++++++++++++++++++++++++++++#033[0m|
Sep  9 20:39:33 ip-10-53-2-218 pull-sandbox-image.sh: layer-sha256:41d8806bd3d23e1ffb7e9825fa56a0c2e851dfeeb405477ab1d6bc3a34bc0da2:    done           |#033[32m++++++++++++++++++++++++++++++++++++++#033[0m|
Sep  9 20:39:33 ip-10-53-2-218 pull-sandbox-image.sh: config-sha256:106a8e54d5eb3f70fcd1ed46255bdf232b3f169e89e68e13e4e67b25f59c1315:   done           |#033[32m++++++++++++++++++++++++++++++++++++++#033[0m|
Sep  9 20:39:33 ip-10-53-2-218 pull-sandbox-image.sh: elapsed: 0.2 s                                                                    total:   0.0 B (0.0 B/s)
Sep  9 20:39:33 ip-10-53-2-218 pull-sandbox-image.sh: unpacking linux/amd64 sha256:1cb4ab85a3480446f9243178395e6bee7350f0d71296daeb6a9fdd221e23aea6...
Sep  9 20:39:33 ip-10-53-2-218 pull-sandbox-image.sh: done
Sep  9 20:39:33 ip-10-53-2-218 systemd: Started pull sandbox image defined in containerd config.toml.
Sep  9 20:39:33 ip-10-53-2-218 systemd: Failed to load environment files: No such file or directory
Sep  9 20:39:33 ip-10-53-2-218 systemd: kubelet.service failed to run 'start-pre' task: No such file or directory
Sep  9 20:39:33 ip-10-53-2-218 systemd: Failed to start Kubernetes Kubelet.
Sep  9 20:39:33 ip-10-53-2-218 systemd: Unit kubelet.service entered failed state.
Sep  9 20:39:33 ip-10-53-2-218 systemd: kubelet.service failed.
Sep  9 20:39:33 ip-10-53-2-218 systemd: Removed slice User Slice of root.
Sep  9 20:39:38 ip-10-53-2-218 systemd: kubelet.service holdoff time over, scheduling restart.
Sep  9 20:39:38 ip-10-53-2-218 systemd: Stopped Kubernetes Kubelet.
Sep  9 20:39:38 ip-10-53-2-218 systemd: Starting pull sandbox image defined in containerd config.toml...
Sep  9 20:39:39 ip-10-53-2-218 systemd: Created slice User Slice of root.
`

I tried to create the file containerd-config.toml empty for tests but other errors came.

Thanks all.
