### ISSUE TITLE
EKS Private Cluster broken example

### ISSUE THREAD

**Issue by boris154** [awsdocs/amazon-eks-user-guide#549]
It seems that the example under "AWS STS endpoints for IAM roles for service accounts" in `doc_source/private-clusters.md` is broken (the YAML format is incorrect and the spec missing some data).

I assume it meant to be:
```yaml
containers:
  - env:
    - name: AWS_REGION
      value: region-code
    - name: AWS_STS_REGIONAL_ENDPOINTS
      value: regional
    ...
```
