### ISSUE TITLE
Confusing guidance on EKS Fargate pod launches for k8s 1.23

### ISSUE THREAD

**Issue by corkupine** [awsdocs/amazon-eks-user-guide#677]
Of concern is this statement:

> Amazon EKS Fargate pod launches might break for pod specs with maximum container resource limits exceeding the sum of requested resources. For guaranteed scheduling, the maximum of resource limits should always be less than the sum of the requested resources.

So does this mean that the limit for container1 is ok, but not for container2?

```
containers:
- name: container1
  resources:
    requests: 
      memory: "2Gi"
    limits:
      memory: "3Gi" # under the total request of 4Gi, so OK
- name: container1
  resources:
    requests: 
      memory: "2Gi"
    limits:
      memory: "5Gi" # over the total request of 4Gi, so may cause pod to not get scheduled
```

And what about a pod with a single container? I wouldn't think we'd want the limit to be less than the request in that case:

```
containers:
- name: container1
  resources:
    requests: 
      memory: "2Gi"
    limits:
      memory: "2Gi" # the sum of requests is 2Gi, so this should be LESS?
```

This also seems to conflict with guidance [here](https://docs.aws.amazon.com/eks/latest/userguide/fargate-pod-configuration.html)

> the requested CPU and memory must be equal to the limit for all of the containers

Would it be best to just avoid specifying limits at all for containers that will be scheduled on to Fargate pods?

This is the best interpretation I can come up with, but wanted to make sure. It also seems a bit strange! Thanks in advance for your help.
