### ISSUE TITLE
Typo in doc_source/dashboard-tutorial.md

### ISSUE THREAD

**Issue by kerbachi** [awsdocs/amazon-eks-user-guide#702]
Following k8s official documentation https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

The section (file doc_source/dashboard-tutorial.md)

```
kubectl apply -f -eks-admin-service-account.yaml << EOF
apiVersion: v1
kind: Secret
metadata:
name: eks-admin
namespace: kube-system
annotations:
kubernetes.io/service-account.name: eks-admin
type: kubernetes.io/service-account-token
EOF
```

should be retyped with correct identations as follow

```
kubectl apply -f eks-admin-service-account.yaml << EOF
apiVersion: v1
kind: Secret
metadata:
  name: eks-admin
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: eks-admin
type: kubernetes.io/service-account-token
EOF
```
