### ISSUE TITLE
"autoModeEnabled" field doesn't exist in eksctl config schema

### ISSUE THREAD

**Issue by aaronzshey** [awsdocs/amazon-eks-user-guide#817]
In the [quickstart guide](https://docs.aws.amazon.com/eks/latest/userguide/quickstart.html), we are instructed to create a `config.yaml` file with the following content:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: web-quickstart
  region: <region-code>

autoModeConfig:
  enabled: true
```

However, running `eksctl create cluster -f cluster-config.yaml` immediately after will throw the error:

```
Error: loading config file "cluster-config.yaml": error unmarshaling JSON: while decoding JSON: json: 
unknown field "autoModeConfig"
```

This field is also absent from the [eksctl config schema](https://eksctl.io/usage/schema/).
